var questionArray = [
{question:"what is capital of Brazil",
a:"Tbilisi",
b:"Brasilia",
c:"Rio dejaneiro",
d:"Sokhumi",
answer:"Brasilia",
image:"brassil.png"
},
{question:"What is the capital of Spain?",
a:"Madrid",
b:"Barcelona",
c:"Ankara",
d:"Antayla",
answer:"Madrid",
image:"spain.png"
},
{question:"what is capital of south African Republice?",
a:"Milan",
b:"Yerevan",
c:"Pretoria",
d:"Cairo ",
answer:"Pretoria",
image:"sf.GIF"
},
{question:"What is the capital of Mexico",
a:"Astana",
b:"Almaty",
c:"New york",
d:"Mexico City",
answer:"Mexico City",
image:"mexico.GIF"
},
{question:"What is the capital of Azerbaijan",
a:"Zakatala",
b:"Batumi",
c:"Kutaisi",
d:"Baku",
answer:"Baku",
image:"azerbaijan.GIF"
},
{question:"What is the capital of Georgia",
a:"Samegrelo",
b:"Batumi",
c:"Tbilisi",
d:"Guria",
answer:"Tbilisi",
image:"georgia.jpg"
}]