var questionArray = [
{question:"What is the capital of Georgia?",
a:"Tbilisi",
b:"Zugdidi",
c:"Kutaisi",
d:"Sokhumi",
answer:"Tbilisi",
image:"georgia.svg"
},
{question:"What is the capital of Turkey?",
a:"Istanbul",
b:"Trabzon",
c:"Ankara",
d:"Antayla",
answer:"Ankara"
},
{question:"What is the capital of Italy?",
a:"Milan",
b:"Rome",
c:"Naples",
d:"Venice",
answer:"Rome"
},
{question:"What is the capital of Kazakhstan?",
a:"Astana",
b:"Almaty",
c:"Atyrau",
d:"Aqtau",
answer:"Astana"
},
{question:"where brazil is located?",
a:"asia",
b:"africa",
c:"south america",
d:"north america",
answer:"south america"
},
{question:"what country is the smallest in the world?",
a:"russian federation",
b:"monaco",
c:"vatican",
d:"tuvalu",
answer:"vatican"
},
{question:"which mountain is the biggest in the world?",
a:"Nanga Parbat",
b:"everest",
d:"Cho Oyu",
answer:"everest"
},
{question:"what is the solution for 2+2*2?",
a:"6",
b:"8",
c:"4",
d:"neither of them",
answer:"6"
},
{question:"which city is the capital city of france?",
a:"Marseille",
b:"Le Mans",
c:"Toulouse",
d:"paris",
answer:"paris"
},
{question:"what is the solution for 5/5*5?",
a:"5",
b:"25",
c:"1",
d:"neither of them",
answer:"5"
},
{question:"what is the solution for 10*10/10*10",
a:"100",
b:"10",
c:"1",
d:"neither of them",
answer:"100"
},
{question:"which country has the highest population in the world?",
a:"india",
b:"bangladesh",
c:"tuvalu",
d:"china",
answer:"china"
},
{question:"did you like the test?",
a:"yes you like it",
b:"no you don't like it",
c:"",
d:"",
answer:"yes you like it"}]